apiVersion: v1
kind: Secret
metadata:
  name: webapp
  namespace: k8s-workshop
type: Opaque
data:
  val1: aXRfaXNfYV9zZWNyZXRfdG9fZXZlcnlib2R5
  val2: ZW5lbWllcz1hbGllbnMKbGl2ZXM9MwplbmVtaWVzLmNoZWF0PXRydWUKZW5lbWllcy5jaGVhdC5sZXZlbD1ub0dvb2RSb3R0ZW4Kc2VjcmV0LmNvZGUucGFzc3BocmFzZT1VVURETFJMUkJBQkFTCnNlY3JldC5jb2RlLmFsbG93ZWQ9dHJ1ZQpzZWNyZXQuY29kZS5saXZlcz0zMAoK
