apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
  namespace: k8s-workshop
spec:
  minReplicas: 1
  maxReplicas:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  targetCPUUtilizationPercentage:
